## Travis CI Integration
language: csharp

matrix:
  include:
    - os: linux
      dist: eoan
      mono: latest
      dotnet: 3.1

before_script:
- git lfs install
- git lfs pull

script:
- ./build.sh --target=Travis --verbosity=diagnostic
