## Travis CI Integration
language: csharp

matrix:
  include:
    - os: linux
      dist: bionic
      mono: latest
      dotnet: 2.2

before_script:
- git lfs install
- git lfs pull

script:
- ./build.sh --target=Travis --verbosity=diagnostic
