## Travis CI Integration
language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      mono: latest
      dotnet: 2.2
    - os: osx
      osx_image: xcode10
      mono: latest
      dotnet: 2.2.401

before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew install git-lfs
  else
    sudo apt-get clean
    sudo apt-get update
    sudo apt-get install dpkg
  fi

before_script:
- git lfs install
- git lfs pull

script:
- ./build.sh --target=Travis --verbosity=diagnostic
